### ISSUE TITLE
CORS upload problem

### ISSUE THREAD

**Issue by Casburggraaf** [adolfintel/speedtest#152]
I have installed the speedteset backend with node with a nginx proxy. It's running from speedtest.xx.com en the front end is on xx.com
Download and ping is working only the upload gives the CORS error.
``
Failed to load https://speedtest.xx.com/empty?r=0.8671990938718868: Request header field Content-Encoding is not allowed by Access-Control-Allow-Headers in preflight response.
``

My nginx config for the speedtest.xx.com:
```
server {

        #root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name speedtest.xx.com;

        location / {

        if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                add_header 'Content-Length' 0;
                return 204;
        }
        if ($request_method = 'POST') {

                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Credentials' 'true';
                add_header 'Access-Control-Allow-Headers' 'Content-Type,Accept';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        }

        if ($request_method = 'GET') {

                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Credentials' 'true';
                add_header 'Access-Control-Allow-Headers' 'Content-Type,Accept';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        }


        proxy_pass http://localhost:8888;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        }
    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = speedtest.xx.coml) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        listen [::]:80;

        server_name speedtest.xx.com;
    return 404; # managed by Certbot


}
```

Tested on all mayor browser and upload is working fine if using this plugin.. https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi

**Comment by adolfintel** [comment]
The master branch will not work cross-origin, even with CORS headers, it triggers bugs in the CORS implementation of most browsers.
You might be interested in the [mpot branch](https://github.com/adolfintel/speedtest/tree/mpot), which is where I implemented cross-domain testing. I haven't tested it on nginx but it should work.

Let me know if you need help, write here or at info@fdossena.com

**Comment by Casburggraaf** [comment]
For future reference, this nginx is working. Will look into the new branch but it's working for now. Thanks!

```
server {

        #root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name speedtest.xxx.nl;

        location / {

        if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'POST';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Access-Control-Allow-Headers' 'content-encoding';
                add_header 'Access-Control-Expose-Headers' 'access-control-allow-origin,access-control-allow-methods,access-control-allow-headers';
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                return 200;
        }
        if ($request_method = 'POST') {

                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Credentials' 'true';
                add_header 'Access-Control-Allow-Headers' 'Content-Type,Accept';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
                add_header 'Access-Control-Expose-Headers' 'access-control-allow-origin,access-control-allow-methods,access-control-allow-headers';
        }

        if ($request_method = 'GET') {

                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Credentials' 'true';
                add_header 'Access-Control-Allow-Headers' 'Content-Type,Accept';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        }


        proxy_pass http://localhost:8888;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot

}
server {
    if ($host = speedtest.xxx.nl) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        listen [::]:80;

        server_name speedtest.glasnet.nl;
    return 404; # managed by Certbot
}
```

**Comment by thgoebel** [comment]
An addendum for future readers:

With the updates made to LibreSpeed by now, you don't need the three `if ($request_method = 'METHOD') {` blocks anymore.
Still, these lines were crucial for me:
```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'upgrade';
proxy_cache_bypass $http_upgrade;
```
Without them during the upload test, CORS on nginx would only work for the OPTIONS requests, but for POST requests it would still fail.

And of course, set `client_max_body_size` to something sensible.

**Comment by PolNavarro** [comment]
Put on nginx:
`     client_max_body_size           5G;
`
